### PR TITLE
Add support for NULL, {} and []

### PR DESCRIPTION
**Pull request by amrith**
Bumps version to 0.7.1, and adds support for NULL, {} and []. NULL is now allowed within a map or a list. Also, empty maps and lists.

*Issue #, if available:* https://github.com/awslabs/dynamodb-shell/issues/17

*Description of changes:*

Bumps version to 0.7.1, and adds support for NULL, {} and []. NULL is now allowed within a map or a list. Also, empty maps and lists.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by amrith** [comment]
@damshenas here you go.

**Comment by damshenas** [comment]
Thanks for the quick fix! I will compile and check ASAP.

**Comment by damshenas** [comment]
I can confirm that this PR fixes the issue https://github.com/awslabs/dynamodb-shell/issues/17 
Thanks for the effort.

**Comment by damshenas** [comment]
Perhaps in this PR you can also fix a consistency issue in the README file by removing line 152 (cd dynamodb-shell) so it work the same way as build steps explain at line 76.

**Comment by damshenas** [comment]
And 1 question. Can we use Null in the where clause? like `WHERE contains(details.field1, null);`
I tried it and it did not work. It is not a use case for me but good to have. Thanks.

**Comment by amrith** [comment]
> And 1 question. Can we use Null in the where clause? like `WHERE contains(details.field1, null);` I tried it and it did not work. It is not a use case for me but good to have. Thanks.

I'll add this as an independent issue, it isn't a quick fix unfortunately.

**Pull request merged**
